'use client';

import { useRef } from 'react';
import { Cube, Code, FileText, Wrench } from '@phosphor-icons/react';
import { Card } from '@/components/ui';
import { useStagger } from '@/lib/animations';
import { messages } from '@/config';

interface Feature {
  icon: typeof Cube;
  title: string;
  description: string;
}

const features: Feature[] = [
  {
    icon: Cube,
    title: 'Component System',
    description:
      'Pre-built dynamic components with configurable properties and slots. Layouts, sliders, tabs, typography, all without touching raw HTML.',
  },
  {
    icon: Code,
    title: 'Attribute Codebase',
    description:
      '40+ modules loaded from a single script. Handles animations, schema generation, sliders, forms, preloading, and accessibility automatically.',
  },
  {
    icon: FileText,
    title: 'CMS Templates',
    description:
      'Homepage mockups generated by AI with custom copy, colors, and layout variants. Service area and FAQ templates built for SEO.',
  },
  {
    icon: Wrench,
    title: 'Developer Toolkit',
    description:
      messages.features.devToolkit,
  },
];

export function Features() {
  const gridRef = useRef<HTMLDivElement>(null);

  useStagger(gridRef, '[data-feature-card]', {
    stagger: 0.15,
    y: 40,
    duration: 0.7,
  });

  return (
    <section className="py-section-sm md:py-section">
      <div className="max-w-6xl mx-auto px-6">
        <h2 className="text-3xl md:text-4xl text-text-primary font-serif text-center mb-16">
          The System
        </h2>

        <div
          ref={gridRef}
          className="grid grid-cols-1 md:grid-cols-2 gap-6"
        >
          {features.map((feature) => {
            const IconComponent = feature.icon;
            return (
              <Card key={feature.title} data-feature-card>
                <IconComponent
                  className="w-8 h-8 text-accent mb-4"
                  weight="duotone"
                />
                <h3 className="text-xl font-medium text-text-primary mb-2">
                  {feature.title}
                </h3>
                <p className="text-text-muted leading-relaxed">
                  {feature.description}
                </p>
              </Card>
            );
          })}
        </div>
      </div>
    </section>
  );
}
